name: Continuous Integration

on: [push]

jobs:
  sanitytests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          ls ${{ github.workspace }}
      # - run: bash -x ${{ github.workspace }}/docs/sanitytests.sh
      - run: bash ${{ github.workspace }}/docs/sanitytests.sh
